### ISSUE TITLE
Automatic subscription to created issues

### ISSUE THREAD

**Issue by JesperNJessen** [nashmaniac/create-issue-action#7]
When I use this action to create issues, it seems as though I am automatically subscribed to them and I receive e-mail notifications when they are closed. I do not receive e-mail notifications for any other issues I (manually) create.

Is there a way to change this?

Workflow file:

```
name: Create test issues for closed issues

on:
  issues:
    types: [closed]
jobs:
  Create_Test_Issue:
    if: contains(github.event.issue.labels.*.name, 'needs test')
    runs-on: ubuntu-latest
    steps:
    - uses: nashmaniac/create-issue-action@v1.1
      with:
        title: "TEST: ${{github.event.issue.title}}"
        token: ${{ secrets.ACTION_TOKEN }}
        labels: test
        body: | 
          Test of #${{github.event.issue.number}}
          ${{github.event.issue.body}}
```
